### ISSUE TITLE
Where code?

### ISSUE THREAD

**Issue by cleankod** [tienbm90/redis-tls-docker-compose#1]
Where's the code? 😄 This repository appears empty. I was looking for a nice solution to test my Redis with SSL configuration. Please push the code, especially the `gen-test-certs.sh` file because this part can be tricky if done improperly.

**Comment by robe007** [comment]
You can see a copy of the `gen-test-certs.sh` file [here](https://github.com/redis/redis/blob/unstable/utils/gen-test-certs.sh)

**Comment by tienbm90** [comment]
> Where's the code? smile This repository appears empty. I was looking for a nice solution to test my Redis with SSL configuration. Please push the code, especially the `gen-test-certs.sh` file because this part can be tricky if done improperly.

Sorry @cleankod and everyone for my late reply. I have missed github notifications until i saw the notification about robe007 comment.

 I pushed my code to the main branch
